"""full schema from schema.sql

Revision ID: 2fd04aeedf1b
Revises: 
Create Date: 2026-07-17 00:39:29.944601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '2fd04aeedf1b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Расширения Postgres (нужны до создания таблиц: vector — колонка articles.embedding,
    # pg_trgm/unaccent — полнотекстовый и триграммный поиск, Фаза 7).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('researcher_works',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('orcid', sa.Text(), nullable=False),
    sa.Column('put_code', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('work_type', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('container', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('email_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('achievements',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('date_received', sa.Date(), nullable=True),
    sa.Column('achievement_type', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('affiliations',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('organization_name', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('provider_id', sa.Text(), nullable=False),
    sa.Column('identity_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_id', name='identities_provider_uq')
    )
    op.create_table('profile_stats',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_publications', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_citations', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('h_index', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('profile_views', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), server_default=sa.text("'authenticated'::text"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('orcid_id', sa.Text(), nullable=True),
    sa.Column('workplace', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('education', sa.Text(), nullable=True),
    sa.CheckConstraint("orcid_id IS NULL OR orcid_id ~ '^\\d{4}-\\d{4}-\\d{4}-\\d{3}[\\dX]$'", name='profiles_orcid_id_check'),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('research_interests',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_links',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journals',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('site_link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('issn', sa.Text(), nullable=True),
    sa.Column('vak', sa.Text(), nullable=True),
    sa.Column('google_scholar', sa.Text(), nullable=True),
    sa.Column('slug', sa.Text(), server_default=sa.text("''::text"), nullable=False),
    sa.Column('cover_image', sa.Text(), nullable=True),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('printed_issn', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('theme', sa.Text(), nullable=True),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('logo', sa.Text(), nullable=True),
    sa.Column('subject_codes', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('type', sa.Text(), server_default=sa.text("'journal'::text"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("type = ANY (ARRAY['journal'::text, 'conference_series'::text])", name='journals_type_check'),
    sa.ForeignKeyConstraint(['admin_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publishers',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name='publishers_slug_check'),
    sa.ForeignKeyConstraint(['admin_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('issues',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('year', sa.BigInteger(), nullable=True),
    sa.Column('volume', sa.Text(), nullable=True),
    sa.Column('issue', sa.Text(), nullable=True),
    sa.Column('journal_id', sa.BigInteger(), nullable=True),
    sa.Column('full_pdf', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('isbn', sa.Text(), nullable=True),
    sa.Column('cover_image', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_admins',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('journal_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('Journal name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'journal_id')
    )
    op.create_table('conference_sections',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('issue_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('title_foreign', sa.Text(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('pages', sa.Text(), nullable=True),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('annotation', sa.Text(), nullable=True),
    sa.Column('annotation_foreign', sa.Text(), nullable=True),
    sa.Column('field_of_science', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('keywords_foreign', sa.Text(), nullable=True),
    sa.Column('pdf', sa.Text(), nullable=True),
    sa.Column('issue_id', sa.BigInteger(), nullable=True),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('data', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('document_ru', postgresql.TSVECTOR(), nullable=True),
    sa.Column('document_en', postgresql.TSVECTOR(), nullable=True),
    sa.Column('document_uz', postgresql.TSVECTOR(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('published', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=True),
    sa.Column('publication_type', sa.Text(), server_default=sa.text("'article'::text"), nullable=False),
    sa.Column('isbn', sa.Text(), nullable=True),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('cover_image', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('publisher_id', sa.BigInteger(), nullable=True),
    sa.Column('section_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("publication_type = ANY (ARRAY['article'::text, 'monograph'::text, 'dissertation'::text, 'textbook'::text, 'methodical'::text, 'book'::text, 'popular'::text, 'conference_paper'::text])", name='articles_publication_type_check'),
    sa.CheckConstraint('data <= CURRENT_DATE', name='articles_data_check'),
    sa.ForeignKeyConstraint(['admin_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['conference_sections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_authors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('author_order', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.Text(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('orcid', sa.Text(), nullable=True),
    sa.CheckConstraint("orcid IS NULL OR orcid ~ '^\\d{4}-\\d{4}-\\d{4}-\\d{3}[\\dX]$'", name='article_authors_orcid_check'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('view', sa.Numeric(), nullable=True),
    sa.Column('download', sa.Numeric(), nullable=True),
    sa.Column('like', sa.Numeric(), nullable=True),
    sa.Column('dislike', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('cited_article_id', sa.BigInteger(), nullable=True),
    sa.Column('cited_doi', sa.Text(), nullable=True),
    sa.Column('raw', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['cited_article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_citations',
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('cited_by_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('counts_by_year', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('source', sa.Text(), server_default=sa.text("'openalex'::text"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_table('saved_articles',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_articles')
    op.drop_table('external_citations')
    op.drop_table('article_references')
    op.drop_table('article_interactions')
    op.drop_table('article_authors')
    op.drop_table('articles')
    op.drop_table('conference_sections')
    op.drop_table('journal_admins')
    op.drop_table('issues')
    op.drop_table('publishers')
    op.drop_table('journals')
    op.drop_table('social_links')
    op.drop_table('research_interests')
    op.drop_table('profiles')
    op.drop_table('profile_stats')
    op.drop_table('identities')
    op.drop_table('affiliations')
    op.drop_table('achievements')
    op.drop_table('users')
    op.drop_table('researcher_works')
    # ### end Alembic commands ###
