"""initial_schema

Revision ID: 6dd6b1ae76a3
Revises: 
Create Date: 2026-02-09 00:49:23.366517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dd6b1ae76a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('site_link', sa.Text(), nullable=True),
    sa.Column('issn', sa.Text(), nullable=True),
    sa.Column('printed_issn', sa.Text(), nullable=True),
    sa.Column('vak', sa.Text(), nullable=True),
    sa.Column('google_scholar', sa.Text(), nullable=True),
    sa.Column('cover_image', sa.Text(), nullable=True),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('theme', sa.Text(), nullable=True),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('logo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issues',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('year', sa.BigInteger(), nullable=True),
    sa.Column('volume', sa.Text(), nullable=True),
    sa.Column('issue', sa.Text(), nullable=True),
    sa.Column('journal_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('title_foreign', sa.Text(), nullable=True),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('pages', sa.Text(), nullable=True),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('annotation', sa.Text(), nullable=True),
    sa.Column('annotation_foreign', sa.Text(), nullable=True),
    sa.Column('field_of_science', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('keywords_foreign', sa.Text(), nullable=True),
    sa.Column('pdf', sa.Text(), nullable=True),
    sa.Column('issue_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('document_ru', postgresql.TSVECTOR(), nullable=True),
    sa.Column('document_en', postgresql.TSVECTOR(), nullable=True),
    sa.Column('document_uz', postgresql.TSVECTOR(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('view', sa.Numeric(), nullable=True),
    sa.Column('download', sa.Numeric(), nullable=True),
    sa.Column('like', sa.Numeric(), nullable=True),
    sa.Column('dislike', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_interactions')
    op.drop_table('articles')
    op.drop_table('issues')
    op.drop_table('journals')
    # ### end Alembic commands ###
